updates:
- directory: /
  package-ecosystem: maven
  schedule:
    interval: daily
  target-branch: main
- directory: /
  package-ecosystem: maven
  schedule:
    interval: daily
  target-branch: 1.1.0
version: 2
