# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "1.0.0"
    schedule:
      interval: "daily"
     
# - directory: /
#   package-ecosystem: maven
#   schedule:
#     interval: daily
#   target-branch: master
# - directory: /
#   package-ecosystem: maven
#   schedule:
#     interval: daily
#   target-branch: 1.0.0
#   - directory: /
#     package-ecosystem: maven
#     schedule:
#       interval: daily
#     target-branch: bug-fixes
#   - directory: /
#     package-ecosystem: maven
#     schedule:
#       interval: daily
#     target-branch: 1.1.0
#   - directory: /
#     package-ecosystem: maven
#     schedule:
#       interval: daily
#     target-branch: 1.1.0.1