#Github
dependabot: '.github/dependabot.yml'
github_actions: '.github/workflows/**/*'
github: '.github/**/*'
gitignore: '**/*.gitignore'
labels: ['.github/labeler.yml', '.github/workflows/labeler.yml']

#Dependencies
gradle: [ 'gradlew', 'gradlew.bat', 'settings.gradle', 'build.gradle', 'gradle/**/*' ]
dependencies: [ 'build.gradle' ]

# Paths
website: 'pages/*'
source: 'src/main/**/*'
tests: 'src/test/**/*'
resources: [ 'src/test/resources/**/*', 'src/main/resources/**/*' ]

#File Formats
java: '**/*.java'
javascript: '**/*.js'
python: '**/*.py'
markdown: '**/*.md'
css: '**/*.css'
json: '**/*.json'
yml: '**/*.yml'
html: '**/*.html'
shell: '**/*.sh'