name: Gradle CI

on:
  push:
    branches: [ main ]
  pull_request_target:
  schedule:
    - cron: '0 0 * * 0'


jobs:
#  build:
#    name: Build
#
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
#    runs-on: ${{matrix.os}}
#    steps:
##    sudo apt-get install dbus-x11
#    - name: Checkout Repository
#      uses: actions/checkout@v3
#    - name: Set up Java
#      uses: actions/setup-java@v3
#      with:
#        java-version: 18
#        distribution: 'temurin'
#        cache: 'gradle'
#    - name: Make Gradlew Executable
#      run: chmod +x gradlew
#    - name: Headless Build with Gradle
#      if: matrix.os != 'windows-latest'
#      uses: GabrielBB/xvfb-action@v1
#      with:
#        run: gradle build --no-daemon
#    - name: Build with Gradle
#      if: matrix.os == 'windows-latest'
#      run: gradle build --no-daemon
#  build-ubuntu:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Required Packages
#        run: |
#          sudo apt install -y dbus-x11 at-spi2-core
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#      - name: Set Up Java
#        uses: actions/setup-java@v3
#        with:
#          java-version: 18
#          distribution: 'temurin'
#          cache: 'gradle'
#      - name: Make gradle executable
#        run: chmod +x gradlew
#      - name: Headless Build with Gradle
#        uses: GabrielBB/xvfb-action@v1
#        with:
#            run: gradle test
#  build-macos:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#      - name: Set Up Java
#        uses: actions/setup-java@v3
#        with:
#          java-version: 18
#          distribution: 'temurin'
#          cache: 'gradle'
#      - name: Make gradle executable
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: gradle test
##      - name: Headless Build with Gradle
##        uses: GabrielBB/xvfb-action@v1
##        with:
##          run: gradle test --no-daemon -Djdk.gtk.version=2
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradle Executable
        run: chmod +x gradlew
      - name: Build with Gradle
        run: gradle test --no-daemon

  tests:
    name: "Tests Completed"
    needs:
#      - build-ubuntu
#      - build-macos
      - build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Completed Tests
        run: echo "Tests completed"
  javadoc:
    name: Javadocs
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
    needs:
      - tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Headless Build with Gradle
        uses: GabrielBB/xvfb-action@v1
        with:
            run: gradle javadoc --no-daemon
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./build/docs/javadoc