name: Gradle CI

on:
  push:
    branches: [ main ]
  pull_request_target:
  schedule:
    - cron: '0 0 * * 0'


jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: 'temurin'
        cache: 'gradle'
    - name: Make Gradlew Executable
      run: chmod +x gradlew
    - name: Headless Build with Gradle
      if: matrix.os != 'windows-latest'
      uses: GabrielBB/xvfb-action@v1
      with:
        run: gradle build --no-daemon
    - name: Build with Gradle
      if: matrix.os == 'windows-latest'
      run: gradle build --no-daemon
  tests:
    name: "Tests Completed"
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Completed Tests
        run: echo "Tests completed"
  javadoc:
    name: Javadocs
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'push' || github.event_name == 'schedule'}}
    needs:
      - tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
          cache: 'gradle'
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Headless Build with Gradle
        uses: GabrielBB/xvfb-action@v1
        with:
            run: gradle javadoc --no-daemon