name: Gradle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Setup xvfb
      if: ${{matrix.os}} == "ubuntu-latest"
      run: |
        Xvfb :99 &>/dev/null &
        export DISPLAY=:99
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: 'temurin'
        cache: 'gradle'
    - name: Make Gradlew Executable
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          build
          -Pheadless=true
