name: Gradle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: 'temurin'
        cache: 'gradle'
    - name: Make Gradlew Executable
      run: chmod +x gradlew
    - name: Headless Build with Gradle
      if: matrix.os != 'windows-latest'
      uses: GabrielBB/xvfb-action@v1
      with:
        run: gradle build
    - name: Build with Gradle
      if: matrix.os == 'windows-latest'
      run: gradle build
