name: Gradle CI

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        gradlescript: [ build ]
        java: [16, 17]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'gradle'
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{github.repository}}/${{github.head_ref}}-gradle-${{runner.os}}-${{matrix.java}}-${{hashFiles('**/*.gradle','**/*.gradle-wrapper.properties')}}
        restore-keys: |
          ${{github.repository}}/${{github.head_ref}}-gradle-${{runner.os}}-${{matrix.java}}-
          ${{github.repository}}/${{github.head_ref}}-gradle-${{runner.os}}-
          ${{github.repository}}/${{github.head_ref}}-gradle-
    - name: Make Gradlew Executable
      run: chmod +x gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ${{ matrix.gradlescript }}
