name: Github Pages

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]
  schedule:
    - cron: '15 14 * * *'

jobs:
  build-pages:
    name: "Build Pages"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha}}
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Set up Node 17
        uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: Update Pip
        run: python -m pip install --upgrade pip
      - name: Install Python Dependencies
        run: python -m pip install -r ./pages/python/requirements.txt
      - name: Install Javascript Dependencies
        working-directory: ./pages
        run: npm install
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Build Javadocs with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc
      - name: Run Python Script
        working-directory: ./pages
        run: python python/build.py
      - name: Run Node Compile
        working-directory: ./pages
        run: npm run compile
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if:  ${{github.event_name == 'push' || github.event_name == 'schedule'}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pages/out
