name: Github Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 14 * * *'

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradlew Executable
        run: chmod +x gradlew
      - name: Build Javadocs with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc
      - name: Run pages.sh build script
        run: ./pages.sh
      - name: Remove Gitignore
        run: rm ./pages/.gitignore
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pages
