# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Publish Javadocs

on:
  push: 
    branches: [ main ]

env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Find Github Token
        if env.GH_TOKEN == '':
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Javadocs with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: javadoc
      - name: Move Javadocs to ./docs folder
        run: |
          rm -r "./docs"
          mv "./build/docs/javadoc" "./docs"
      - name: Push to Main
        run: |
          git config --local user.name 'github-actions'
          git config --local user.email 'github-actions@github.com'
          git add .
          git commit -am "Generate Javadocs"
          git push
